### PR TITLE
Update pybind11 from 2.2 to 2.3

### PR DESCRIPTION
**Pull request by renefritze**
this fixes using a dbg python interpreter

### CODE REVIEW

**Comment by renefritze** [comment]
This still needs needs a way to automatically set `PYTHON_IS_DEBUG` when a matching interpreter is used.

**Comment by renefritze** [comment]
Have a look at https://github.com/dune-community/dune-pybindxi/pull/9/commits/00c9e8f35b2368c1a1e5a00ec1585188ed4fbb35 @ftalbrecht

**Comment by ftalbrecht** [comment]
Is this ready to be merged, @renefritze?

**Comment by renefritze** [comment]
Go ahead. That needs the mini changes in one of the xt-modules then.

**Pull request merged**
