### PR TITLE
[WIP] Be compatible with dune-common 2.6

### PR DESCRIPTION
**Pull request by tobiasleibner**
This contains the necessary changes to make the dune-xt modules work with dune-common 2.6 and without dune-python.

### CODE REVIEW

**Comment by renefritze** [comment]
Was there a blocker for merging this?

**Comment by ftalbrecht** [comment]
No, but I'll add a few more commits and then merge.

**Comment by ftalbrecht** [comment]
We don't have any CI for this module, do we? I am ready to merge here, but doing so will break all dependent modules. I will prepare prs to pudate those and would this wait with merging this pr...

**Comment by renefritze** [comment]
No, there's no CI.

**Comment by renefritze** [comment]
You need to merge this PR and/or update the ref in the super module before your downstream PRs can begin to succeed. Otherwise the docker images still have the old version of this module.

**Pull request merged**
